import Logo1 from './logos/logo1.svg';
import Logo2 from './logos/logo2.svg';
import Logo3 from './logos/logo3.svg';
import Logo4 from './logos/logo4.svg';
import Logo5 from './logos/logo5.svg';
import Logo6 from './logos/logo6.svg';
import Logo7 from './logos/logo7.svg';
import Logo8 from './logos/logo8.svg';
import Logo9 from './logos/logo9.svg';
import Logo10 from './logos/logo10.svg';
export default [Logo1, Logo2, Logo3, Logo4, Logo5, Logo6, Logo7, Logo8, Logo9, Logo10];
